import './globals.css'
import Navigation from '@/components/navigation/navigation'
import Footer from '@/components/footer/footer'
import Newsletter from '@/components/newsletter/page'
import { Providers } from '@/components/provider'


export const metadata = {
  title: 'K&K RECORDS',
  description: 'Generated by create next app',
}

console.log("Greetings from K&K Media Group Sweden AB. This was a fun project and hopefully you'll be interested in K&K Records.");


export default function RootLayout(
  {
  children,
  }: 
  {
  children: React.ReactNode
  }
  
)
 {
  return (
    <html lang="SE_sv" suppressHydrationWarning>
      <link rel="manifest" href="/public/manifest.json" />
      <script 
      data-goatcounter="https://kkrecords.goatcounter.com/count"
      async src="//gc.zgo.at/count.js">
      </script>
      <script type="text/javascript" 
      src="//cdn.cookie-script.com/s/a4be59e1f9e75da3214c98f0d1417fd3.js"></script>
      <body>
        <Providers> 
        <Navigation/>
          <main className="min-h-screen">
            {children}
          </main>
          <Newsletter/>
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
