import './globals.css'
import Navigation from '@/components/navigation/navigation'
import Footer from '@/components/footer/footer'
import { Providers } from '@/components/provider'
import Cursor from '@/components/cursor/cursor'
import Newsletter from '@/components/newsletter/page'
import CookieBanner from '@/components/CookieBanner'


export const metadata = {
  title: 'K&K RECORDS',
  description: 'Generated by create next app',
}

console.log("Greetings from K&K Media Group Sweden AB. This was a fun project and hopefully you'll be interested in K&K Records.");



export default function RootLayout(
  {
  children,
  }: 
  {
  children: React.ReactNode
  }
  
)
 {
  return (
    <html lang="SE_sv" suppressHydrationWarning>
      <script 
      data-goatcounter="https://kkrecords.goatcounter.com/count"
      async src="//gc.zgo.at/count.js">
      </script>
      <script async src="//instant.page/5.2.0" type="module" integrity="sha384-jnZyxPjiipYXnSU0ygqeac2q7CVYMbh84q0uHVRRxEtvFPiQYbXWUorga2aqZJ0z"></script>
      <body className=" bg-white dark:bg-black border-black dark:border-white border-4">
        <Cursor/>
        <CookieBanner/>
        <Providers> 
        <Navigation/>
          <main>
            {children}
          </main>
          
          <Newsletter/>
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
